platform_name: Android
automation_name: UiAutomator2
device_name: Samsung Galaxy S9 Plus FHD GoogleAPI Emulator
platform_version: "8.1"
app: storage:filename=Android.SauceLabs.apk
app_package: com.swaglabsmobileapp
app_activity: .MainActivity
app_wait_activity: "*"
app_wait_duration: 60000
new_command_timeout: 180
no_reset: false
full_reset: true
auto_grant_permissions: true
sauce_options:
  name: Android - Smoke
  build: local
