name: Manual Run (Sauce)

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "android or ios"
        required: true
        default: "android"
      markers:
        description: 'pytest -m expression'
        required: true
        default: 'smoke and sauce'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RUN_ENV: ci
      APPIUM_SERVER_URL: ${{ secrets.SAUCE_APPIUM_URL }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_REGION: ${{ secrets.SAUCE_REGION }}
      PLATFORM: ${{ inputs.platform }}
      ANDROID_SAUCE_APP: ${{ secrets.ANDROID_SAUCE_APP }}
      IOS_SAUCE_APP: ${{ secrets.IOS_SAUCE_APP }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare report dirs
        run: |
          mkdir -p reports/allure-results reports/artifacts

      - name: Build Docker image
        run: docker compose -f docker/compose.yml build

      - name: Run Tests
        run: |
          docker compose -f docker/compose.yml run --rm tests \
            pytest -m "${{ inputs.markers }}" -q

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results
          if-no-files-found: ignore


      - name: Upload Failure Artifacts (screenshots + xml)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-artifacts-${{ github.run_id }}
          path: reports/artifacts
          if-no-files-found: ignore
